Ruby on Rails web application/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :sections
  resources :semesters
  resources :courses
  resources :prefixes
  resources :students
  
  resources :searches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

Ruby on Rails web application/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :semester
  has_and_belongs_to_many :students

  # validates crn from 10000 to 100000 and uniqueness in database
  validates :Crn, numericality: {greater_than: 10000, less_than: 100000}, uniqueness: true
  # Validations
  #validates_associated :students
  #validates :course, presence: true
  #validates :semester, presence: true
  #validates :Crn, length:{ is:5}

end

Ruby on Rails web application/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]

  # GET /sections or /sections.json
  def index
   # @sections = Section.all
  #  @sections = Section.joins(:Course).joins(:Semester).joins("LEFT JOIN Prefixes ON Prefixes.id = Courses.Prefix_id").where(
  #   "CRN LIKE ?
  #   OR Prefixes.prefix || Courses.number LIKE ?
  #   OR semesters.semester LIKE ?
  #   OR semesters.year LIKE ?
  #   OR semesters.semester || ' ' || semesters.year LIKE ?",
  #   "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    @students = Student.all
    if params[:query]
      @sections = Section.where("Crn like ?", "%#{params[:query]}%")
    else
      @sections = Section.all
    end
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    @students = Student.all
  end

  # GET /sections/1/edit
  def edit
    @students = Student.all
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to section_url(@section), notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to section_url(@section), notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:Crn, :course_id, :semester_id)
      params.require(:section).permit(:Crn, :course_id, :semester_id, :student_ids => [])
    end
end

Ruby on Rails web application/app/helpers/sections_helper.rb
module SectionsHelper
end

Ruby on Rails web application/app/views/sections/_form.html.erb
<!--<%= stylesheet_link_tag "application.css" %>-->
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Crn, style: "display: block"%>
    <%= form.number_field :Crn %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.collection_select :course_id, Course.all, :id, :name%>
   <!-- <%= form.text_field :course_id %>-->
  </div>

  <div>
    <%= form.label :semester_id, style: "display: block" %>
    <%= form.collection_select :semester_id, Semester.all, :id, :semester%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby on Rails web application/app/views/sections/_section.html.erb
<div id="<%= dom_id section %>">
  <p>
    <strong>Crn:</strong>
    <%= section.Crn %>
  </p>

  <p>
    <strong>Course:</strong>
    <% if section.course != nil %>
       <%= section.course.name%>
    <% else %>
       <%= "Unknown name!" %>
    <% end%>
  </p>
  <p>
    <strong>Semester:</strong>
    <% if section.semester != nil %>
       <%=section.semester.semester%>
    <% else %>
       <%= "Unknown semester!" %>
    <% end%>
  </p>
    <p>
            <strong>Students:</strong>
            <%counter = 1%>
            <% section.students.each do |student| %>
                <%= "#{counter}: #{student.student_name}, "%>
                <%counter += 1%>
            <% end %>
        </p>

</div>

Ruby on Rails web application/app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Show this section", @section %> |
  <%= link_to "Back to sections", sections_path %>
</div>

Ruby on Rails web application/app/views/sections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sections</h1>
<%=form_tag(sections_url, method:"get") do %>
  <%= label_tag(:query, "Enter crn to search for:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<div id="sections">
  <% @sections.each do |section| %>
    <%= render section %>
    <p>
      <%= link_to "Show this section", section %>
    </p>
  <% end %>
</div>

<%= link_to "New section", new_section_path %>

Ruby on Rails web application/app/views/sections/new.html.erb
<h1>New section</h1>

<%= render "form", section: @section %>

<br>

<div>
  <%= link_to "Back to sections", sections_path %>
</div>

Ruby on Rails web application/app/views/sections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @section %>

<div>
  <%= link_to "Edit this section", edit_section_path(@section) %> |
  <%= link_to "Back to sections", sections_path %>

  <%= button_to "Destroy this section", @section, method: :delete %>
</div>